music-streaming-data-pipeline:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: music-streaming-data-pipeline
      dataset: music-streaming-data-pipeline-stg
      location: US
      threads: 4
      timeout_seconds: 300
      priority: interactive
      retries: 1
    prod:
      type: bigquery
      method: service-account
      project: music-streaming-data-pipeline
      dataset: music-streaming-data-pipeline-prod
      location: US
      threads: 4
      timeout_seconds: 300
      priority: interactive
      retries: 1